-- -------------------------------------------------------------
-- 
-- File Name: testzzadanymfreq3/lookupTable/lookupTable_pkg.vhd
-- Created: 2020-01-14 23:05:21
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE lookupTable_pkg IS
  TYPE vector_of_signed18 IS ARRAY (NATURAL RANGE <>) OF signed(17 DOWNTO 0);
END lookupTable_pkg;

