-- -------------------------------------------------------------
-- 
-- File Name: testzzadanymfreq3/lookupTable/lookupTable.vhd
-- Created: 2020-01-14 23:05:21
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-06
-- Target subsystem base rate: 1e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- SinWave                       ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: lookupTable
-- Source Path: lookupTable
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY lookupTable IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        SinWave                           :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En17
        );
END lookupTable;


ARCHITECTURE rtl OF lookupTable IS

  -- Component Declarations
  COMPONENT Triggered_Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          In1                             :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En8
          Trigger                         :   IN    std_logic;  -- ufix1
          Out1                            :   OUT   std_logic_vector(17 DOWNTO 0)  -- sfix18_En17
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Triggered_Subsystem
    USE ENTITY work.Triggered_Subsystem(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Constant_out1                    : signed(17 DOWNTO 0);  -- sfix18_En8
  SIGNAL HDL_Counter_out1                 : std_logic;  -- ufix1
  SIGNAL Triggered_Subsystem_out1         : std_logic_vector(17 DOWNTO 0);  -- ufix18

BEGIN
  u_Triggered_Subsystem : Triggered_Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              In1 => std_logic_vector(Constant_out1),  -- sfix18_En8
              Trigger => HDL_Counter_out1,  -- ufix1
              Out1 => Triggered_Subsystem_out1  -- sfix18_En17
              );

  Constant_out1 <= to_signed(16#0010D#, 18);

  enb <= clk_enable;

  -- Count limited, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  --  count to value  = 1
  HDL_Counter_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      HDL_Counter_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        HDL_Counter_out1 <=  NOT HDL_Counter_out1;
      END IF;
    END IF;
  END PROCESS HDL_Counter_process;


  ce_out <= clk_enable;

  SinWave <= Triggered_Subsystem_out1;

END rtl;

